

import StringIO

import tfd.fasta


# Error message added as first argument to Exceptions raised during
# FASTA file parsing.  Usage example:
# try:
#     ...
# raise Exception as e:
#     if e.args and e.args[0] == PARSING_ERROR:
#         ...
#     else: 
#         raise


TEST_FASTA_IN = {'GOOD_TEST': '''>ns|id|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
''',
              'LONG_TEST': '''>ns|id|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
>ns|id2|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
''',
              'BLANK_IN_TEST': '''>ns|id|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
  
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
''',
              'BLANK_START_TEST': '''  
>ns|id|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
''',
              'DATA_START_TEST': '''CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
>ns|id|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
''',
              'TWO_NAMELINES_TEST': '''>ns|id|a long description
>ns|id2|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
''',
              'TRAILING_NAMELINE_TEST': '''>ns|id|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
>ns|id2|a long description
''',
                 'TRAILING_BLANK': '''>ns|id|a long description
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA
CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA

'''}

TEST_FASTA_OUT = { 
    'GOOD_TEST': [['>ns|id|a long description\n',
                   'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                   'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n']],
    'LONG_TEST': [['>ns|id|a long description\n',
                   'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                   'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n'],
                  ['>ns|id2|a long description\n',
                   'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                   'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n']],
    'BLANK_IN_TEST': [['>ns|id|a long description\n',
                       'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                       'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n']],
    'BLANK_START_TEST': [['>ns|id|a long description\n',
                          'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                          'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n']],
    'DATA_START_TEST': [['>ns|id|a long description\n',
                         'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                         'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n']],
    'TWO_NAMELINES_TEST': [['>ns|id2|a long description\n',
                            'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                            'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n']],
    'TRAILING_NAMELINE_TEST': [['>ns|id|a long description\n',
                                'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                                'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n']],
    'TRAILING_BLANK': [['>ns|id|a long description\n',
                        'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n',
                        'CTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGA\n']],
}


def test_reading_lines():
    for name in TEST_FASTA_IN:
        outputs = list(tfd.fasta.readFastaLines(StringIO.StringIO(TEST_FASTA_IN[name])))
        assert outputs == TEST_FASTA_OUT[name]


